version: '3.8'

services:
  frontend:
    image: ${FRONTEND_IMAGE}
    container_name: frontend-container
    ports:
      - "80:3000"
    depends_on:
      - backend

  backend:
    image: ${BACKEND_IMAGE}
    container_name: backend-container
    ports:
      - "8080:8080"