version: '3.8'

services:
  backend:
    image: backend-app:1.0
    container_name: backend-container
    ports:
      - "8080:8080"
    restart: always
  frontend:
    image: frontend-app:1.0
    container_name: frontend-container
    ports:
      - "80:80"
    restart: always